version: '3'

services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /tmp/influxdbrelay-influx:/var/lib/influxdb

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  relay:
    build:
      context: ../
      dockerfile: Dockerfile.develop
    ports:
      - "9096:9096"

  debug:
    image: debian
    stdin_open: true
    tty: true
