[[http]]
name = "test-config"
bind-addr = "0.0.0.0:9096"
output = [
    { name="from_influx", location = "http://127.0.0.1:8086/write" },
    { name="from_prometheus", location = "http://127.0.0.1:8086/api/v1/prom/write", type="prometheus" }
]
